import unittest
import unittest.mock

from wdcuration.wikipedia import get_qids_from_enwiki_pages


class TestWikipediaTools(unittest.TestCase):
    def test_get_qids_from_enwiki_pages(self):
        target = {
            "Anatomy": "Q514",
            "Angola": "Q916",
            "Antarctic": "Q1555938",
            "Antimony": "Q1099",
            "Arachnid": "Q1358",
            "Astrobiology": "Q411",
            "Bahrain": "Q398",
            "Belgium": "Q31",
            "Brazil": "Q155",
            "Chaetobranchus": "Q3460",
            "Chicago": "Q1297",
            "Chile": "Q298",
            "Computer": "Q68",
            "Flower": "Q506",
            "French Guiana": "Q3769",
            "Fungus": "Q764",
            "Gadolinium": "Q1832",
            "Geography": "Q1071",
            "Germany": "Q183",
            "Happiness": "Q8",
            "Illinois": "Q1204",
            "Internet": "Q75",
            "Israel": "Q801",
            "Laos": "Q819",
            "Liberty": "Q2979",
            "Lion": "Q140",
            "Mali": "Q912",
            "Malta": "Q233",
            "Massachusetts": "Q771",
            "Metabolism": "Q1057",
            "Mississippi": "Q1494",
            "New Mexico": "Q1522",
            "Newfoundland and Labrador": "Q2003",
            "North Sea": "Q1693",
            "Planet": "Q634",
            "Platinum": "Q880",
            "Portugal": "Q45",
            "Potassium bromide": "Q2546",
            "Proton": "Q2294",
            "Puerto Rico": "Q1183",
            "Sierra Leone": "Q1044",
            "Solar System": "Q544",
            "Sudan": "Q1049",
            "Tajikistan": "Q863",
            "Thailand": "Q869",
            "Titanium": "Q716",
            "United Arab Emirates": "Q878",
            "Vanadium": "Q722",
            "Vanuatu": "Q686",
            "World War II": "Q362",
            "15th century": "Q7018",
            "18th century": "Q7015",
            "Actinopodidae": "Q5845",
            "Artery": "Q9655",
            "Bashkortostan": "Q5710",
            "Cithaeronidae": "Q8631",
            "Dall sheep": "Q576112",
            "Desidae": "Q10038",
            "Dictynidae": "Q10049",
            "Ecology": "Q7150",
            "Epineurium": "Q988861",
            "Genetics": "Q7162",
            "Hepatitis B virus": "Q6844",
            "Herpesvirales": "Q6542",
            "Human herpesvirus 6": "Q6974",
            "Human mouth": "Q1370895",
            "Human rights": "Q8458",
            "Idiopidae": "Q10579",
            "Investment": "Q4290",
            "Joint": "Q9644",
            "Kidney": "Q9377",
            "Kinorhyncha": "Q5182",
            "Lynx spider": "Q10970",
            "Map": "Q4006",
            "Marriage": "Q8445",
            "Mecysmaucheniidae": "Q10631",
            "Mother": "Q7560",
            "Multiple sclerosis": "Q8277",
            "Muscle tissue": "Q797559",
            "Myasthenia gravis": "Q8285",
            "Nicodamidae": "Q10961",
            "Oecobiidae": "Q10966",
            "Onychophora": "Q5191",
            "Orsolobidae": "Q10969",
            "Phyxelididae": "Q10997",
            "Probability": "Q9492",
            "Rabbit": "Q9394",
            "Red squirrel": "Q4388",
            "Religion": "Q9174",
            "Sac spider": "Q8634",
            "Snow": "Q7561",
            "Spaceflight": "Q5916",
            "Squirrel": "Q9482",
            "Swimming": "Q6388",
            "Tax": "Q8161",
            "Technology": "Q11016",
            "Tree trunk spider": "Q10553",
            "Vein": "Q9609",
            "Wandering spider": "Q8708",
            "Wind": "Q8094",
        }
        result = get_qids_from_enwiki_pages(
            [
                "Belgium",
                "Happiness",
                "Portugal",
                "Antarctic",
                "Computer",
                "Internet",
                "Lion",
                "Brazil",
                "Germany",
                "Malta",
                "Chile",
                "World War II",
                "Bahrain",
                "Astrobiology",
                "Flower",
                "Anatomy",
                "Solar System",
                "Planet",
                "Vanuatu",
                "Titanium",
                "Vanadium",
                "Fungus",
                "Massachusetts",
                "Israel",
                "Laos",
                "Tajikistan",
                "Thailand",
                "United Arab Emirates",
                "Platinum",
                "Mali",
                "Angola",
                "Sierra Leone",
                "Sudan",
                "Metabolism",
                "Geography",
                "Antimony",
                "Puerto Rico",
                "Illinois",
                "Chicago",
                "Arachnid",
                "Mississippi",
                "New Mexico",
                "North Sea",
                "Gadolinium",
                "Newfoundland and Labrador",
                "Proton",
                "Potassium bromide",
                "Liberty",
                "Chaetobranchus",
                "French Guiana",
                "Map",
                "Investment",
                "Red squirrel",
                "Kinorhyncha",
                "Onychophora",
                "Bashkortostan",
                "Actinopodidae",
                "Spaceflight",
                "Swimming",
                "Herpesvirales",
                "Hepatitis B virus",
                "Human herpesvirus 6",
                "18th century",
                "15th century",
                "Ecology",
                "Genetics",
                "Muscle tissue",
                "Dall sheep",
                "Mother",
                "Snow",
                "Wind",
                "Tax",
                "Multiple sclerosis",
                "Myasthenia gravis",
                "Marriage",
                "Human rights",
                "Cithaeronidae",
                "Sac spider",
                "Wandering spider",
                "Religion",
                "Kidney",
                "Rabbit",
                "Squirrel",
                "Probability",
                "Vein",
                "Epineurium",
                "Human mouth",
                "Joint",
                "Artery",
                "Desidae",
                "Dictynidae",
                "Tree trunk spider",
                "Idiopidae",
                "Mecysmaucheniidae",
                "Nicodamidae",
                "Oecobiidae",
                "Orsolobidae",
                "Lynx spider",
                "Phyxelididae",
                "Technology",
            ]
        )

        self.assertEqual(result, target)
